# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8da8e258c50936191e9fb5f66600c5c6cae47b39c21e76755e3f818e3ca0b612f90197024925c9f8b116a83e16a444fdd16e7efe3255de4e0dbab315926cce54

test:
  secret_key_base: 8b9854a71635e2ef15f20835c576ceabe8ab1563091f5ed3d7f552949c84b0066121ccd865041ab44bbf239ec9305606f309c5c32df0bc0c8f04a18f02fc3347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
